version: "3.8"
services:
  android-service:
    build: .
    ports:
      - 4725:4725
      - 5900:5900
    container_name: android
    environment:
      - APPIUM_PORT=4725
      - VNC_PASSWORD=123
    privileged: true
    command:
      - bash
      - -c
      - |
         ./start.sh
    tty: true
